'use client';

import React, { useState } from 'react';
import { Card, Typography, Select, DatePicker, Button, Row, Col, Table } from 'antd';
import { BarChartOutlined, FileTextOutlined, FolderOutlined, DollarOutlined, DownloadOutlined, PlusOutlined } from '@ant-design/icons';
import { useRouter } from 'next/navigation';
import { PageShell, StatCard, GradientButton } from '@/components/design-system';

const { Option } = Select;
const { Title, Text } = Typography;

export default function ReportsPage() {
  const router = useRouter();
  const [reportType, setReportType] = useState<string | undefined>();
  const [category, setCategory] = useState<string | undefined>();

  const reportCategories = [
    {
      key: 'clinical',
      name: 'Clinical Reports',
      description: 'Patient outcomes, diagnoses, treatments',
      icon: <FileTextOutlined />,
      color: '#3B82F6',
      bg: '#DBEAFE',
      border: '#93C5FD',
      count: 24,
      path: '/reports/clinical',
    },
    {
      key: 'operational',
      name: 'Operational Reports',
      description: 'Bed occupancy, staff efficiency, wait times',
      icon: <BarChartOutlined />,
      color: '#10B981',
      bg: '#D1FAE5',
      border: '#A7F3D0',
      count: 18,
      path: '/reports/utilization',
    },
    {
      key: 'financial',
      name: 'Financial Reports',
      description: 'Revenue, expenses, billing, claims',
      icon: <DollarOutlined />,
      color: '#F59E0B',
      bg: '#FEF3C7',
      border: '#FDE68A',
      count: 32,
      path: '/reports/financial',
    },
    {
      key: 'inventory',
      name: 'Inventory Reports',
      description: 'Stock levels, consumption, expiry',
      icon: <FolderOutlined />,
      color: '#8B5CF6',
      bg: '#EDE9FE',
      border: '#DDD6FE',
      count: 15,
      path: '/reports',
    },
  ];

  const recentReports = [
    {
      key: '1',
      name: 'Monthly Patient Statistics',
      category: 'Clinical',
      generated: '2024-02-01',
      generatedBy: 'Admin',
      status: 'ready',
    },
    {
      key: '2',
      name: 'Q4 Financial Summary',
      category: 'Financial',
      generated: '2024-01-31',
      generatedBy: 'Finance',
      status: 'ready',
    },
    {
      key: '3',
      name: 'Bed Occupancy Report',
      category: 'Operational',
      generated: '2024-02-01',
      generatedBy: 'Admin',
      status: 'ready',
    },
    {
      key: '4',
      name: 'Department Performance',
      category: 'Clinical',
      generated: '2024-02-02',
      generatedBy: 'Medical Director',
      status: 'generating',
    },
  ];

  const columns = [
    {
      title: 'Report Name',
      dataIndex: 'name',
      key: 'name',
      render: (name: string, record: any) => (
        <div className="flex items-center gap-2">
          <FileTextOutlined style={{ color: '#3B82F6' }} />
          <span className="font-medium">{name}</span>
        </div>
      ),
    },
    {
      title: 'Category',
      dataIndex: 'category',
      key: 'category',
      render: (category: string) => (
        <span
          style={{
            padding: '4px 10px',
            borderRadius: '6px',
            fontSize: '13px',
            fontWeight: 500,
            background: category === 'Clinical'
              ? '#DBEAFE'
              : category === 'Financial'
              ? '#FEF3C7'
              : category === 'Operational'
              ? '#D1FAE5'
              : '#EDE9FE',
            color: category === 'Clinical'
              ? '#1E40AF'
              : category === 'Financial'
              ? '#92400E'
              : category === 'Operational'
              ? '#065F46'
              : '#5B21B6',
          }}
        >
          {category}
        </span>
      ),
    },
    { title: 'Generated', dataIndex: 'generated', key: 'generated' },
    { title: 'Generated By', dataIndex: 'generatedBy', key: 'generatedBy' },
    {
      title: 'Actions',
      key: 'actions',
      render: (_: unknown, record: any) => (
        <Button
          size="small"
          icon={<DownloadOutlined />}
          disabled={record.status !== 'ready'}
          style={{
            borderRadius: '8px',
            fontWeight: 500,
          }}
        >
          Download
        </Button>
      ),
    },
  ];

  return (
    <PageShell
      title="Reports & Analytics"
      subtitle="Comprehensive hospital reporting and insights"
      action={
        <GradientButton icon={<PlusOutlined />}>
          New Report
        </GradientButton>
      }
    >
      {/* Statistics Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6">
        <StatCard
          label="Total Reports"
          value={89}
          color="#3B82F6"
          bg="linear-gradient(135deg, #DBEAFE 0%, rgba(255,255,255,0.8) 100%)"
          border="#93C5FD"
          index={0}
        />
        <StatCard
          label="This Month"
          value={24}
          color="#10B981"
          bg="linear-gradient(135deg, #D1FAE5 0%, rgba(255,255,255,0.8) 100%)"
          border="#A7F3D0"
          index={1}
        />
        <StatCard
          label="Scheduled"
          value={12}
          color="#F59E0B"
          bg="linear-gradient(135deg, #FEF3C7 0%, rgba(255,255,255,0.8) 100%)"
          border="#FDE68A"
          index={2}
        />
        <StatCard
          label="In Progress"
          value={5}
          color="#8B5CF6"
          bg="linear-gradient(135deg, #EDE9FE 0%, rgba(255,255,255,0.8) 100%)"
          border="#DDD6FE"
          index={3}
        />
      </div>

      {/* Report Categories */}
      <div style={{ background: 'white', borderRadius: '12px', padding: '24px', border: '1px solid #E2E8F0', marginBottom: '24px' }} className="p-4 sm:p-6">
        <div className="flex items-center gap-2 mb-4">
          <FolderOutlined style={{ color: '#3B82F6', fontSize: '20px' }} />
          <h2 className="text-lg font-semibold text-gray-900">Report Categories</h2>
        </div>
        <Row gutter={[16, 16]}>
          {reportCategories.map((cat) => (
            <Col xs={12} sm={6} key={cat.key}>
              <div
                onClick={() => router.push(cat.path)}
                style={{
                  padding: '20px',
                  borderRadius: '12px',
                  background: `linear-gradient(135deg, ${cat.bg} 0%, rgba(255,255,255,0.8) 100%)`,
                  border: `1px solid ${cat.border}`,
                  cursor: 'pointer',
                  transition: 'all 0.3s ease',
                  position: 'relative',
                  overflow: 'hidden',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = 'translateY(-4px)';
                  e.currentTarget.style.boxShadow = `0 12px 24px -8px ${cat.color}`;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = 'translateY(0)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    marginBottom: '12px',
                  }}
                >
                  <div
                    style={{
                      width: '48px',
                      height: '48px',
                      borderRadius: '10px',
                      background: `linear-gradient(135deg, ${cat.color} 0%, ${cat.color}99 100%)`,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: 'white',
                      fontSize: '20px',
                    }}
                  >
                    {cat.icon}
                  </div>
                  <div style={{ flex: 1 }}>
                    <h3 className="text-sm font-semibold text-gray-900 mb-1">
                      {cat.name}
                    </h3>
                    <Text style={{ fontSize: '12px', color: '#64748B' }}>
                      {cat.description}
                    </Text>
                  </div>
                </div>
                <div
                  style={{
                    padding: '4px 10px',
                    borderRadius: '6px',
                    background: 'white',
                    border: `1px solid ${cat.border}`,
                    display: 'inline-block',
                  }}
                >
                  <Text style={{ fontSize: '12px', fontWeight: 600, color: cat.color }}>
                    {cat.count} reports
                  </Text>
                </div>
              </div>
            </Col>
          ))}
        </Row>
      </div>

      {/* Generate Custom Report */}
      <div style={{ background: 'white', borderRadius: '12px', padding: '24px', border: '1px solid #E2E8F0', marginBottom: '24px' }} className="p-4 sm:p-6">
        <div className="flex items-center gap-2 mb-4">
          <PlusOutlined style={{ color: '#10B981', fontSize: '20px' }} />
          <h2 className="text-lg font-semibold text-gray-900">Generate Custom Report</h2>
        </div>
        <Row gutter={16}>
          <Col span={6}>
            <label className="block text-sm mb-2 font-medium" style={{ color: '#374151' }}>
              Report Type
            </label>
            <Select
              placeholder="Select type"
              value={reportType}
              onChange={setReportType}
              style={{ width: '100%', borderRadius: '8px' }}
            >
              <Option value="summary">Summary Report</Option>
              <Option value="detailed">Detailed Report</Option>
              <Option value="statistical">Statistical Analysis</Option>
            </Select>
          </Col>
          <Col span={6}>
            <label className="block text-sm mb-2 font-medium" style={{ color: '#374151' }}>
              Category
            </label>
            <Select
              placeholder="Select category"
              value={category}
              onChange={setCategory}
              style={{ width: '100%', borderRadius: '8px' }}
            >
              <Option value="clinical">Clinical</Option>
              <Option value="operational">Operational</Option>
              <Option value="financial">Financial</Option>
              <Option value="inventory">Inventory</Option>
            </Select>
          </Col>
          <Col span={6}>
            <label className="block text-sm mb-2 font-medium" style={{ color: '#374151' }}>
              Date Range
            </label>
            <DatePicker.RangePicker style={{ width: '100%', borderRadius: '8px' }} />
          </Col>
          <Col span={6}>
            <label className="block text-sm mb-2 font-medium" style={{ color: '#374151' }}>
              &nbsp;
            </label>
            <GradientButton icon={<PlusOutlined />} block>
              Generate Report
            </GradientButton>
          </Col>
        </Row>
      </div>

      {/* Recent Reports */}
      <div style={{ background: 'white', borderRadius: '12px', padding: '24px', border: '1px solid #E2E8F0' }} className="p-4 sm:p-6">
        <div className="flex items-center justify-between mb-4 flex-col sm:flex-row gap-3">
          <div className="flex items-center gap-2">
            <FileTextOutlined style={{ color: '#8B5CF6', fontSize: '20px' }} />
            <h2 className="text-lg font-semibold text-gray-900">Recent Reports</h2>
          </div>
          <Button
            type="link"
            style={{ color: '#3B82F6', fontWeight: 500 }}
            onClick={() => router.push('/reports/clinical')}
            className="w-full sm:w-auto"
          >
            View All
          </Button>
        </div>
        <div className="overflow-x-auto">
          <Table
            dataSource={recentReports}
            columns={columns}
            pagination={false}
            size="middle"
            className="modern-table"
          />
        </div>
      </div>

      <style jsx global>{`
        .modern-table .ant-table-thead > tr > th {
          background: linear-gradient(180deg, #F8FAFC 0%, #F1F5F9 100%) !important;
          border-bottom: 2px solid #E2E8F0 !important;
          font-weight: 600;
          color: #1E293B;
          padding: 14px 16px !important;
          font-size: 13px;
        }
        .modern-table .ant-table-tbody > tr > td {
          padding: 12px 16px !important;
          border-bottom: 1px solid #F1F5F9 !important;
        }
        .modern-table .ant-table-tbody > tr:hover > td {
          background: linear-gradient(90deg, #EFF6FF 0%, #F0F9FF 100%) !important;
        }
      `}</style>
    </PageShell>
  );
}
