'use client';

import React, { useState } from 'react';
import { Card, Typography, Select, DatePicker, Button, Row, Col, Table, Alert } from 'antd';
import { BarChartOutlined, FileTextOutlined, FolderOutlined, DollarOutlined, DownloadOutlined, PlusOutlined } from '@ant-design/icons';
import { useRouter } from 'next/navigation';
import { PageShell, StatCard, GradientButton } from '@/components/design-system';
import { useAuth } from '@/lib/contexts/AuthContext';

const { Option } = Select;
const { Title, Text } = Typography;

export default function ReportsPage() {
  const router = useRouter();
  const { hasPermission } = useAuth();
  const [reportType, setReportType] = useState<string | undefined>();
  const [category, setCategory] = useState<string | undefined>();

  if (!hasPermission('reports:view') && !hasPermission('reports:clinical:view')) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-blue-50 to-slate-50 ">
        <Alert
          title="Access Denied"
          description="You don't have permission to access reports. Please contact your administrator."
          type="error"
          showIcon
          className=" "
        />
      </div>
    );
  }

  const canViewFinancial = hasPermission('reports:financial:view');
  const canViewOperational = hasPermission('reports:utilization:view') || hasPermission('reports:operational:view');
  const canViewClinical = hasPermission('reports:clinical:view') || hasPermission('reports:patient:view');

  const reportCategories = [
    {
      key: 'clinical',
      name: 'Clinical Reports',
      description: 'Patient outcomes, diagnoses, treatments',
      icon: <FileTextOutlined />,
      color: '#3B82F6',
      bg: '#DBEAFE',
      border: '#93C5FD',
      count: 24,
      path: '/reports/clinical',
    },
    {
      key: 'operational',
      name: 'Operational Reports',
      description: 'Bed occupancy, staff efficiency, wait times',
      icon: <BarChartOutlined />,
      color: '#10B981',
      bg: '#D1FAE5',
      border: '#A7F3D0',
      count: 18,
      path: '/reports/utilization',
    },
    {
      key: 'financial',
      name: 'Financial Reports',
      description: 'Revenue, expenses, billing, claims',
      icon: <DollarOutlined />,
      color: '#F59E0B',
      bg: '#FEF3C7',
      border: '#FDE68A',
      count: 32,
      path: '/reports/financial',
    },
    {
      key: 'inventory',
      name: 'Inventory Reports',
      description: 'Stock levels, consumption, expiry',
      icon: <FolderOutlined />,
      color: '#8B5CF6',
      bg: '#EDE9FE',
      border: '#DDD6FE',
      count: 15,
      path: '/reports',
    },
  ].filter((cat) => {
    if (cat.key === 'financial') return canViewFinancial;
    if (cat.key === 'operational') return canViewOperational;
    if (cat.key === 'inventory') return hasPermission('reports:inventory:view') || hasPermission('reports:view');
    return canViewClinical;
  });

  const recentReports = [
    {
      key: '1',
      name: 'Monthly Patient Statistics',
      category: 'Clinical',
      generated: '2024-02-01',
      generatedBy: 'Admin',
      status: 'ready',
    },
    {
      key: '2',
      name: 'Q4 Financial Summary',
      category: 'Financial',
      generated: '2024-01-31',
      generatedBy: 'Finance',
      status: 'ready',
    },
    {
      key: '3',
      name: 'Bed Occupancy Report',
      category: 'Operational',
      generated: '2024-02-01',
      generatedBy: 'Admin',
      status: 'ready',
    },
    {
      key: '4',
      name: 'Department Performance',
      category: 'Clinical',
      generated: '2024-02-02',
      generatedBy: 'Medical Director',
      status: 'generating',
    },
  ];

  const columns = [
    {
      title: 'Report Name',
      dataIndex: 'name',
      key: 'name',
      render: (name: string, record: any) => (
        <div className="  ">
          <FileTextOutlined className="" />
          <span className="font-medium">{name}</span>
        </div>
      ),
    },
    {
      title: 'Category',
      dataIndex: 'category',
      key: 'category',
      render: (category: string) => (
        <span
          style={{
            padding: '4px 10px',
            
                        fontWeight: 500,
            background: category === 'Clinical'
              ? '#DBEAFE'
              : category === 'Financial'
              ? '#FEF3C7'
              : category === 'Operational'
              ? '#D1FAE5'
              : '#EDE9FE',
            color: category === 'Clinical'
              ? '#1E40AF'
              : category === 'Financial'
              ? '#92400E'
              : category === 'Operational'
              ? '#065F46'
              : '#5B21B6',
          }}
        >
          {category}
        </span>
      ),
    },
    { title: 'Generated', dataIndex: 'generated', key: 'generated' },
    { title: 'Generated By', dataIndex: 'generatedBy', key: 'generatedBy' },
    {
      title: 'Actions',
      key: 'actions',
      render: (_: unknown, record: any) => (
        <Button
          size="small"
          icon={<DownloadOutlined />}
          disabled={record.status !== 'ready'}
          className=" font-medium"
        >
          Download
        </Button>
      ),
    },
  ];

  return (
    <PageShell
      title="Reports & Analytics"
      subtitle="Comprehensive hospital reporting and insights"
      action={
        <GradientButton icon={<PlusOutlined />}>
          New Report
        </GradientButton>
      }
    >
      {/* Statistics Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4  ">
        <StatCard
          label="Total Reports"
          value={89}
          color="#3B82F6"
          bg="linear-gradient(135deg, #DBEAFE 0%, rgba(255,255,255,0.8) 100%)"
          border="#93C5FD"
          index={0}
        />
        <StatCard
          label="This Month"
          value={24}
          color="#10B981"
          bg="linear-gradient(135deg, #D1FAE5 0%, rgba(255,255,255,0.8) 100%)"
          border="#A7F3D0"
          index={1}
        />
        <StatCard
          label="Scheduled"
          value={12}
          color="#F59E0B"
          bg="linear-gradient(135deg, #FEF3C7 0%, rgba(255,255,255,0.8) 100%)"
          border="#FDE68A"
          index={2}
        />
        <StatCard
          label="In Progress"
          value={5}
          color="#8B5CF6"
          bg="linear-gradient(135deg, #EDE9FE 0%, rgba(255,255,255,0.8) 100%)"
          border="#DDD6FE"
          index={3}
        />
      </div>

      {/* Report Categories */}
      <div className=" bg-white   border border-slate-200">
        <div className="   ">
          <FolderOutlined className="color: '#3B82F6' text" />
          <h2 className=" font-semibold ">Report Categories</h2>
        </div>
        <Row gutter={[16, 16]}>
          {reportCategories.map((cat) => (
            <Col xs={12} sm={6} key={cat.key}>
              <div
                onClick={() => router.push(cat.path)}
                style={{
                                    
                  background: `linear-gradient(135deg, ${cat.bg} 0%, rgba(255,255,255,0.8) 100%)`,
                  border: `1px solid ${cat.border}`,
                  cursor: 'pointer',
                  transition: 'all 0.3s ease',
                  position: 'relative',
                  overflow: 'hidden',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = 'translateY(-4px)';
                  e.currentTarget.style.boxShadow = `0 12px 24px -8px ${cat.color}`;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = 'translateY(0)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              >
                <div
                  style={{
                                                                                                  }}
                >
                  <div
                    style={{
                      width: '48px',
                                            
                      background: `linear-gradient(135deg, ${cat.color} 0%, ${cat.color}99 100%)`,
                                                                                                              text
                    }}
                  >
                    {cat.icon}
                  </div>
                  <div className="-1">
                    <h3 className=" font-semibold  ">
                      {cat.name}
                    </h3>
                    <Text className=" text-slate-500">
                      {cat.description}
                    </Text>
                  </div>
                </div>
                <div
                  style={{
                    padding: '4px 10px',
                    
                    
                    border: `1px solid ${cat.border}`,
                    display: 'inline-flex',
                  }}
                >
                  <Text className=" font-semibold" style={{ color: cat.color }}>
                    {cat.count} reports
                  </Text>
                </div>
              </div>
            </Col>
          ))}
        </Row>
      </div>

      {/* Generate Custom Report */}
      <div className=" bg-white   border border-slate-200">
        <div className="   ">
          <PlusOutlined className="color: '#10B981' text" />
          <h2 className=" font-semibold ">Generate Custom Report</h2>
        </div>
        <Row gutter={16}>
          <Col span={6}>
            <label className="block   font-medium ">
              Report Type
            </label>
            <Select
              placeholder="Select type"
              value={reportType}
              onChange={setReportType}
              className="w-full "
            >
              <Option value="summary">Summary Report</Option>
              <Option value="detailed">Detailed Report</Option>
              <Option value="statistical">Statistical Analysis</Option>
            </Select>
          </Col>
          <Col span={6}>
            <label className="block   font-medium ">
              Category
            </label>
            <Select
              placeholder="Select category"
              value={category}
              onChange={setCategory}
              className="w-full "
            >
              <Option value="clinical">Clinical</Option>
              <Option value="operational">Operational</Option>
              <Option value="financial">Financial</Option>
              <Option value="inventory">Inventory</Option>
            </Select>
          </Col>
          <Col span={6}>
            <label className="block   font-medium ">
              Date Range
            </label>
            <DatePicker.RangePicker className="w-full " />
          </Col>
          <Col span={6}>
            <label className="block   font-medium ">
              &nbsp;
            </label>
            <GradientButton icon={<PlusOutlined />} block>
              Generate Report
            </GradientButton>
          </Col>
        </Row>
      </div>

      {/* Recent Reports */}
      <div className="bg-white   border border-slate-200">
        <div className="    -col sm:-row ">
          <div className="  ">
            <FileTextOutlined className="color: '#8B5CF6' text" />
            <h2 className=" font-semibold ">Recent Reports</h2>
          </div>
          <Button
            type="link"
            className="color: '#3B82F6' font-medium w-full sm:w-auto"
            onClick={() => router.push('/reports/clinical')}
          >
            View All
          </Button>
        </div>
        <div className="overflow-x-auto">
          <Table
            dataSource={recentReports}
            columns={columns}
            pagination={false}
            size="middle"
            className="modern-table"
          />
        </div>
      </div>

      <style jsx global>{`
        .modern-table .ant-table-thead > tr > th {
          background: linear-gradient(180deg, #F8FAFC 0%, #F1F5F9 100%) !important;
          border-bottom: 2px solid #E2E8F0 !important;
          font-weight: 600;
          color: #1E293B;
          padding: 14px 16px !important;
          font-size: 13px;
        }
        .modern-table .ant-table-tbody > tr > td {
          padding: 12px 16px !important;
          border-bottom: 1px solid #F1F5F9 !important;
        }
        .modern-table .ant-table-tbody > tr:hover > td {
          background: linear-gradient(90deg, #EFF6FF 0%, #F0F9FF 100%) !important;
        }
      `}</style>
    </PageShell>
  );
}
