// Mock drug data for Pharmacy module
import { Drug } from '@/types';

export const mockDrugs: Drug[] = [
  {
    id: 'drug1',
    name: 'Amoxicillin 500mg Capsule',
    genericName: 'Amoxicillin Trihydrate',
    brandName: 'Amoxil',
    category: 'Antibiotics',
    dosageForm: 'capsule',
    strength: '500mg',
    manufacturer: 'Pfizer',
    unitPrice: 150,
    stock: 2500,
    reorderLevel: 500,
    expiryDate: new Date('2025-06-30'),
    batchNumber: 'AMX-2024-001',
    storage: 'Room Temperature',
    controlled: false,
  },
  {
    id: 'drug2',
    name: 'Paracetamol 500mg Tablet',
    genericName: 'Acetaminophen',
    brandName: 'Panadol',
    category: 'Analgesics',
    dosageForm: 'tablet',
    strength: '500mg',
    manufacturer: 'GSK',
    unitPrice: 50,
    stock: 15000,
    reorderLevel: 3000,
    expiryDate: new Date('2026-12-31'),
    batchNumber: 'PCM-2024-002',
    storage: 'Room Temperature',
    controlled: false,
  },
  {
    id: 'drug3',
    name: 'Ceftriaxone 1g Injection',
    genericName: 'Ceftriaxone Sodium',
    brandName: 'Rocephin',
    category: 'Antibiotics',
    dosageForm: 'injection',
    strength: '1g',
    manufacturer: 'Roche',
    unitPrice: 3500,
    stock: 450,
    reorderLevel: 100,
    expiryDate: new Date('2025-03-31'),
    batchNumber: 'CEF-2024-003',
    storage: 'Refrigerator',
    controlled: false,
  },
  {
    id: 'drug4',
    name: 'Insulin Glargine 100U/ml',
    genericName: 'Insulin Glargine',
    brandName: 'Lantus',
    category: 'Antidiabetic',
    dosageForm: 'injection',
    strength: '100U/ml',
    manufacturer: 'Sanofi',
    unitPrice: 9500,
    stock: 120,
    reorderLevel: 30,
    expiryDate: new Date('2025-09-30'),
    batchNumber: 'INS-2024-004',
    storage: 'Refrigerator',
    controlled: false,
  },
  {
    id: 'drug5',
    name: 'Metformin 500mg Tablet',
    genericName: 'Metformin Hydrochloride',
    brandName: 'Glucophage',
    category: 'Antidiabetic',
    dosageForm: 'tablet',
    strength: '500mg',
    manufacturer: 'Merck',
    unitPrice: 80,
    stock: 8000,
    reorderLevel: 2000,
    expiryDate: new Date('2026-06-30'),
    batchNumber: 'MET-2024-005',
    storage: 'Room Temperature',
    controlled: false,
  },
  {
    id: 'drug6',
    name: 'Amlodipine 10mg Tablet',
    genericName: 'Amlodipine Besylate',
    brandName: 'Norvasc',
    category: 'Cardiovascular',
    dosageForm: 'tablet',
    strength: '10mg',
    manufacturer: 'Pfizer',
    unitPrice: 250,
    stock: 5500,
    reorderLevel: 1000,
    expiryDate: new Date('2026-08-31'),
    batchNumber: 'AML-2024-006',
    storage: 'Room Temperature',
    controlled: false,
  },
  {
    id: 'drug7',
    name: 'Codeine 30mg Tablet',
    genericName: 'Codeine Phosphate',
    brandName: 'Codeine Contin',
    category: 'Analgesics',
    dosageForm: 'tablet',
    strength: '30mg',
    manufacturer: 'Pfizer',
    unitPrice: 450,
    stock: 250,
    reorderLevel: 50,
    expiryDate: new Date('2025-04-30'),
    batchNumber: 'COD-2024-007',
    storage: 'Room Temperature',
    controlled: true,
    schedule: 'V',
  },
  {
    id: 'drug8',
    name: 'Diazepam 5mg Tablet',
    genericName: 'Diazepam',
    brandName: 'Valium',
    category: 'Anticonvulsant',
    dosageForm: 'tablet',
    strength: '5mg',
    manufacturer: 'Roche',
    unitPrice: 850,
    stock: 150,
    reorderLevel: 30,
    expiryDate: new Date('2025-11-30'),
    batchNumber: 'DIA-2024-008',
    storage: 'Room Temperature',
    controlled: true,
    schedule: 'IV',
  },
  {
    id: 'drug9',
    name: 'Salbutamol Inhaler 100mcg',
    genericName: 'Albuterol Sulfate',
    brandName: 'Ventolin',
    category: 'Respiratory',
    dosageForm: 'inhaler',
    strength: '100mcg/dose',
    manufacturer: 'GSK',
    unitPrice: 2500,
    stock: 350,
    reorderLevel: 75,
    expiryDate: new Date('2025-07-31'),
    batchNumber: 'SAL-2024-009',
    storage: 'Room Temperature',
    controlled: false,
  },
  {
    id: 'drug10',
    name: 'Ibuprofen 400mg Tablet',
    genericName: 'Ibuprofen',
    brandName: 'Brufen',
    category: 'NSAID',
    dosageForm: 'tablet',
    strength: '400mg',
    manufacturer: 'Pfizer',
    unitPrice: 120,
    stock: 4200,
    reorderLevel: 800,
    expiryDate: new Date('2026-04-30'),
    batchNumber: 'IBU-2024-010',
    storage: 'Room Temperature',
    controlled: false,
  },
];
