// Extended Mock Data for New Modules
import {
  InsurancePartner,
  PreAuthorization,
  Claim,
  ClaimSettlement,
  PayerTariff,
  Employee,
  Shift,
  RosterEntry,
  AttendanceRecord,
  LeaveRequest,
  LeaveBalance,
  Payroll,
  EmergencyPatient,
  EDBoard,
  EDStats,
  TelemedicineConsultation,
  TelemedicineSlot,
} from '@/types';
import { Department as HRDepartment } from '@/types/hr';

// ==================== INSURANCE MODULE ====================
export const mockInsurancePartners: InsurancePartner[] = [
  {
    id: 'ip1',
    code: 'AXA',
    name: 'AXA Mansard Insurance',
    type: 'insurance',
    category: 'primary',
    contactPerson: 'Chidi Okonkwo',
    email: 'claims@axamansard.com',
    phoneNumber: '+234 1 234 5678',
    address: '15 Awolowo Road, Ikoyi',
    city: 'Lagos',
    state: 'Lagos',
    country: 'Nigeria',
    taxId: '12345678-0001',
    logo: '/logos/axa.png',
    networkType: 'cashless',
    paymentTerms: 30,
    status: 'active',
    contractStart: new Date('2023-01-01'),
    contractEnd: new Date('2026-12-31'),
    panelDoctors: 45,
    panelHospitals: 12,
  },
  {
    id: 'ip2',
    code: 'HYGEIA',
    name: 'Hygeia HMO',
    type: 'tpa',
    category: 'primary',
    contactPerson: 'Grace Adebayo',
    email: 'providers@hygeia.com',
    phoneNumber: '+234 1 345 6789',
    address: '42 Isaac John Street, Ikeja GRA',
    city: 'Lagos',
    state: 'Lagos',
    country: 'Nigeria',
    taxId: '87654321-0001',
    logo: '/logos/hygeia.png',
    networkType: 'cashless',
    paymentTerms: 45,
    status: 'active',
    contractStart: new Date('2023-06-01'),
    panelDoctors: 38,
    panelHospitals: 8,
  },
  {
    id: 'ip3',
    code: 'RELIA',
    name: 'Reliance HMO',
    type: 'tpa',
    category: 'secondary',
    contactPerson: 'Bisi Eze',
    email: 'network@reliancehmo.com',
    phoneNumber: '+234 1 456 7890',
    address: '8 Adetokunbo Ademola Street, Victoria Island',
    city: 'Lagos',
    state: 'Lagos',
    country: 'Nigeria',
    taxId: '11223344-0001',
    logo: '/logos/reliance.png',
    networkType: 'both',
    paymentTerms: 30,
    status: 'active',
    contractStart: new Date('2022-01-01'),
    panelDoctors: 52,
    panelHospitals: 15,
  },
  {
    id: 'ip4',
    code: 'NNHIS',
    name: 'National Health Insurance Scheme',
    type: 'government',
    category: 'primary',
    contactPerson: 'Dr. Ibrahim Musa',
    email: 'operations@nhis.gov.ng',
    phoneNumber: '+234 1 567 8901',
    address: 'Plot 423, Constitution Avenue, Central Business District',
    city: 'Abuja',
    state: 'FCT',
    country: 'Nigeria',
    taxId: '99887766-0001',
    logo: '/logos/nhis.png',
    networkType: 'cashless',
    paymentTerms: 60,
    status: 'active',
    contractStart: new Date('2021-01-01'),
    panelDoctors: 120,
    panelHospitals: 35,
  },
  {
    id: 'ip5',
    code: 'PREST',
    name: 'Prestige Assurance',
    type: 'insurance',
    category: 'secondary',
    contactPerson: 'Ngozi Okafor',
    email: 'health@prestige.com',
    phoneNumber: '+234 1 678 9012',
    address: '25 Gerard Road, Ikoyi',
    city: 'Lagos',
    state: 'Lagos',
    country: 'Nigeria',
    taxId: '55443322-0001',
    logo: '/logos/prestige.png',
    networkType: 'reimbursement',
    paymentTerms: 45,
    status: 'active',
    contractStart: new Date('2023-03-01'),
    contractEnd: new Date('2025-12-31'),
    panelDoctors: 28,
    panelHospitals: 6,
  },
];

export const mockPreAuthorizations: PreAuthorization[] = [
  {
    id: 'pa1',
    preAuthNumber: 'PA-2024-0001',
    patientId: '1',
    patientName: 'Chukwuemeka Okonkwo',
    mrn: 'MRN-2024-0001',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    policyNumber: 'AXA-2023-78456',
    policyHolderName: 'Chukwuemeka Okonkwo',
    relationship: 'self',
    requestedDate: new Date('2024-01-28'),
    requestedBy: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    doctor: 'Dr. Emeka Adeleke',
    diagnosis: 'Hypertensive Heart Disease with Congestive Heart Failure',
    icdCode: 'I11.0',
    procedures: [
      {
        id: 'proc1',
        procedureCode: 'ECHO-001',
        procedureName: '2D Echocardiogram with Doppler',
        category: 'opd',
        estimatedCost: 45000,
        approvedCost: 42000,
        status: 'approved',
      },
      {
        id: 'proc2',
        procedureCode: 'ECG-001',
        procedureName: '12-Lead ECG',
        category: 'opd',
        estimatedCost: 8000,
        approvedCost: 8000,
        status: 'approved',
      },
    ],
    estimatedAmount: 53000,
    approvedAmount: 50000,
    status: 'approved',
    reviewedBy: 'Dr. Chioma Nnamani',
    reviewedDate: new Date('2024-01-29'),
    approvalNumber: 'AXA-APP-2024-0156',
    validFrom: new Date('2024-01-29'),
    validUntil: new Date('2024-02-28'),
    remarks: 'Pre-authorization approved for cardiac evaluation',
    documents: [
      {
        id: 'doc1',
        documentName: 'Doctor Prescription.pdf',
        documentType: 'prescription',
        uploadDate: new Date('2024-01-28'),
        uploadedBy: 'Dr. Emeka Adeleke',
        fileUrl: '/documents/pa1-prescription.pdf',
      },
      {
        id: 'doc2',
        documentName: 'ID Card.jpg',
        documentType: 'id_proof',
        uploadDate: new Date('2024-01-28'),
        uploadedBy: 'Front Desk',
        fileUrl: '/documents/pa1-id.jpg',
      },
    ],
  },
  {
    id: 'pa2',
    preAuthNumber: 'PA-2024-0002',
    patientId: '3',
    patientName: 'Olufemi Adebayo',
    mrn: 'MRN-2024-0003',
    insurancePartnerId: 'ip2',
    insurancePartnerName: 'Hygeia HMO',
    policyNumber: 'HYG-2024-12345',
    policyHolderName: 'Olufemi Adebayo',
    relationship: 'self',
    requestedDate: new Date('2024-02-01'),
    requestedBy: 'Dr. Ibrahim Musa',
    department: 'General Medicine',
    doctor: 'Dr. Ibrahim Musa',
    diagnosis: 'Uncontrolled Type 2 Diabetes Mellitus',
    icdCode: 'E11.65',
    procedures: [
      {
        id: 'proc3',
        procedureCode: 'HBA1C-001',
        procedureName: 'HbA1c Test',
        category: 'opd',
        estimatedCost: 5500,
        status: 'pending',
      },
      {
        id: 'proc4',
        procedureCode: 'LIPID-001',
        procedureName: 'Lipid Profile',
        category: 'opd',
        estimatedCost: 7500,
        status: 'pending',
      },
    ],
    estimatedAmount: 13000,
    status: 'under_review',
    remarks: 'Submitted for TPA review',
    documents: [
      {
        id: 'doc3',
        documentName: 'lab_request.pdf',
        documentType: 'prescription',
        uploadDate: new Date('2024-02-01'),
        uploadedBy: 'Dr. Ibrahim Musa',
        fileUrl: '/documents/pa2-lab-request.pdf',
      },
    ],
  },
  {
    id: 'pa3',
    preAuthNumber: 'PA-2024-0003',
    patientId: '7',
    patientName: 'Tobi Okafor',
    mrn: 'MRN-2024-0007',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    policyNumber: 'AXA-2023-78460',
    policyHolderName: 'Chioma Okafor',
    relationship: 'child',
    requestedDate: new Date('2024-02-02'),
    requestedBy: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    doctor: 'Dr. Aisha Yusuf',
    diagnosis: 'Childhood Asthma Exacerbation',
    icdCode: 'J45.901',
    procedures: [
      {
        id: 'proc5',
        procedureCode: 'PEFR-001',
        procedureName: 'Peak Expiratory Flow Rate',
        category: 'opd',
        estimatedCost: 3500,
        status: 'approved',
      },
      {
        id: 'proc6',
        procedureCode: 'CHEST-XRAY',
        procedureName: 'Chest X-Ray PA View',
        category: 'opd',
        estimatedCost: 12000,
        status: 'approved',
      },
    ],
    estimatedAmount: 15500,
    approvedAmount: 15500,
    status: 'approved',
    reviewedBy: 'Dr. Grace Adebayo',
    reviewedDate: new Date('2024-02-02'),
    approvalNumber: 'AXA-APP-2024-0167',
    validFrom: new Date('2024-02-02'),
    validUntil: new Date('2024-03-02'),
    remarks: 'Emergency pre-auth approved for pediatric patient',
    documents: [],
  },
  {
    id: 'pa4',
    preAuthNumber: 'PA-2024-0004',
    patientId: '2',
    patientName: 'Adanna Okafor',
    mrn: 'MRN-2024-0002',
    insurancePartnerId: 'ip3',
    insurancePartnerName: 'Reliance HMO',
    policyNumber: 'REL-2023-45678',
    policyHolderName: 'Adanna Okafor',
    relationship: 'self',
    requestedDate: new Date('2024-01-30'),
    requestedBy: 'Dr. Chinedu Okonkwo',
    department: 'Orthopedics',
    doctor: 'Dr. Chinedu Okonkwo',
    diagnosis: 'Knee Osteoarthritis',
    icdCode: 'M17.11',
    procedures: [
      {
        id: 'proc7',
        procedureCode: 'KNEE-XR',
        procedureName: 'Knee Joint X-Ray Both Views',
        category: 'opd',
        estimatedCost: 15000,
        status: 'rejected',
      },
    ],
    estimatedAmount: 15000,
    status: 'rejected',
    reviewedBy: 'Dr. Bimpe Alake',
    reviewedDate: new Date('2024-01-31'),
    remarks: 'Procedure not covered under policy - requires specialist referral',
    documents: [],
  },
  {
    id: 'pa5',
    preAuthNumber: 'PA-2024-0005',
    patientId: '5',
    patientName: 'Ibrahim Musah',
    mrn: 'MRN-2024-0005',
    insurancePartnerId: 'ip4',
    insurancePartnerName: 'National Health Insurance Scheme',
    policyNumber: 'NHIS-2021-00123',
    policyHolderName: 'Ibrahim Musah',
    relationship: 'self',
    requestedDate: new Date('2024-02-03'),
    requestedBy: 'Dr. Chioma Nnamani',
    department: 'Neurology',
    doctor: 'Dr. Chioma Nnamani',
    diagnosis: 'Migraine with Aura',
    icdCode: 'G43.109',
    procedures: [
      {
        id: 'proc8',
        procedureCode: 'CT-HEAD',
        procedureName: 'CT Scan Head Plain',
        category: 'opd',
        estimatedCost: 45000,
        status: 'pending',
      },
    ],
    estimatedAmount: 45000,
    status: 'pending',
    remarks: 'Awaiting neurologist review',
    documents: [],
  },
];

export const mockClaims: Claim[] = [
  {
    id: 'clm1',
    claimNumber: 'CLM-2024-0001',
    patientId: '1',
    patientName: 'Chukwuemeka Okonkwo',
    mrn: 'MRN-2024-0001',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    policyNumber: 'AXA-2023-78456',
    claimType: 'cashless',
    admissionDate: new Date('2024-01-15'),
    dischargeDate: new Date('2024-01-18'),
    submittedDate: new Date('2024-01-20'),
    submittedBy: 'Billing Department',
    preAuthId: 'pa1',
    billNumber: 'INV-2024-00456',
    billedAmount: 285000,
    claimedAmount: 250000,
    approvedAmount: 235000,
    settledAmount: 235000,
    status: 'settled',
    reviewedBy: 'Dr. Chioma Nnamani',
    reviewedDate: new Date('2024-01-22'),
    approvedBy: 'Finance Manager',
    approvedDate: new Date('2024-01-23'),
    settlementDate: new Date('2024-01-28'),
    settlementReference: 'PYMT-2024-01234',
    remarks: 'Claim settled as per policy terms',
    documents: [
      {
        id: 'cldoc1',
        documentName: 'Final_Bill.pdf',
        documentType: 'bill',
        uploadDate: new Date('2024-01-20'),
        uploadedBy: 'Billing Department',
        fileUrl: '/documents/clm1-bill.pdf',
      },
      {
        id: 'cldoc2',
        documentName: 'Discharge_Summary.pdf',
        documentType: 'discharge_summary',
        uploadDate: new Date('2024-01-19'),
        uploadedBy: 'Dr. Emeka Adeleke',
        fileUrl: '/documents/clm1-discharge.pdf',
      },
    ],
  },
  {
    id: 'clm2',
    claimNumber: 'CLM-2024-0002',
    patientId: '3',
    patientName: 'Olufemi Adebayo',
    mrn: 'MRN-2024-0003',
    insurancePartnerId: 'ip2',
    insurancePartnerName: 'Hygeia HMO',
    policyNumber: 'HYG-2024-12345',
    claimType: 'cashless',
    submittedDate: new Date('2024-02-01'),
    submittedBy: 'Billing Department',
    billNumber: 'INV-2024-00512',
    billedAmount: 125000,
    claimedAmount: 110000,
    status: 'under_review',
    reviewedBy: 'Claims Officer',
    reviewedDate: new Date('2024-02-03'),
    remarks: 'Claim under review - additional documents requested',
    documents: [
      {
        id: 'cldoc3',
        documentName: 'hospital_bill.pdf',
        documentType: 'bill',
        uploadDate: new Date('2024-02-01'),
        uploadedBy: 'Billing Department',
        fileUrl: '/documents/clm2-bill.pdf',
      },
    ],
  },
  {
    id: 'clm3',
    claimNumber: 'CLM-2024-0003',
    patientId: '2',
    patientName: 'Adanna Okafor',
    mrn: 'MRN-2024-0002',
    insurancePartnerId: 'ip3',
    insurancePartnerName: 'Reliance HMO',
    policyNumber: 'REL-2023-45678',
    claimType: 'reimbursement',
    submittedDate: new Date('2024-01-25'),
    submittedBy: 'Adanna Okafor',
    billNumber: 'INV-2024-00389',
    billedAmount: 68000,
    claimedAmount: 60000,
    approvedAmount: 52000,
    deductionAmount: 8000,
    status: 'approved',
    reviewedBy: 'Dr. Ngozi Eze',
    reviewedDate: new Date('2024-01-27'),
    approvedBy: 'Finance Manager',
    approvedDate: new Date('2024-01-28'),
    deductionReason: 'Non-covered items deducted as per policy',
    remarks: 'Approved for reimbursement - payment in process',
    documents: [],
  },
  {
    id: 'clm4',
    claimNumber: 'CLM-2024-0004',
    patientId: '5',
    patientName: 'Ibrahim Musah',
    mrn: 'MRN-2024-0005',
    insurancePartnerId: 'ip4',
    insurancePartnerName: 'National Health Insurance Scheme',
    policyNumber: 'NHIS-2021-00123',
    claimType: 'cashless',
    admissionDate: new Date('2024-01-28'),
    dischargeDate: new Date('2024-01-31'),
    submittedDate: new Date('2024-02-02'),
    submittedBy: 'Billing Department',
    billNumber: 'INV-2024-00534',
    billedAmount: 185000,
    claimedAmount: 165000,
    status: 'submitted',
    remarks: 'Claim submitted to NHIS',
    documents: [],
  },
  {
    id: 'clm5',
    claimNumber: 'CLM-2024-0005',
    patientId: '7',
    patientName: 'Tobi Okafor',
    mrn: 'MRN-2024-0007',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    policyNumber: 'AXA-2023-78460',
    claimType: 'cashless',
    submittedDate: new Date('2024-02-03'),
    submittedBy: 'Dr. Aisha Yusuf',
    preAuthId: 'pa3',
    billNumber: 'INV-2024-00567',
    billedAmount: 42000,
    claimedAmount: 38000,
    status: 'draft',
    remarks: 'Draft claim - pending review before submission',
    documents: [],
  },
];

export const mockClaimSettlements: ClaimSettlement[] = [
  {
    id: 'stl1',
    settlementNumber: 'STL-2024-0001',
    claimId: 'clm1',
    claimNumber: 'CLM-2024-0001',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    settlementDate: new Date('2024-01-28'),
    settledAmount: 235000,
    paymentMode: 'bank_transfer',
    transactionReference: 'BKTRF-2024-015678',
    bankName: 'Guaranty Trust Bank',
    accountNumber: '0123456789',
    settledBy: 'Accounts Department',
    remarks: 'Payment processed via NEFT',
    status: 'completed',
  },
  {
    id: 'stl2',
    settlementNumber: 'STL-2024-0002',
    claimId: 'clm3',
    claimNumber: 'CLM-2024-0003',
    insurancePartnerId: 'ip3',
    insurancePartnerName: 'Reliance HMO',
    settlementDate: new Date('2024-01-30'),
    settledAmount: 52000,
    paymentMode: 'bank_transfer',
    transactionReference: 'HMO-2024-089012',
    bankName: 'First Bank of Nigeria',
    accountNumber: '0987654321',
    settledBy: 'Accounts Department',
    status: 'completed',
  },
];

export const mockPayerTariffs: PayerTariff[] = [
  {
    id: 'tariff1',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    procedureCode: 'ECHO-001',
    procedureName: '2D Echocardiogram with Doppler',
    category: 'Cardiology',
    roomType: 'general',
    tariffAmount: 42000,
    copayAmount: 5000,
    copayPercentage: 10,
    effectiveDate: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'tariff2',
    insurancePartnerId: 'ip1',
    insurancePartnerName: 'AXA Mansard Insurance',
    procedureCode: 'ECHO-001',
    procedureName: '2D Echocardiogram with Doppler',
    category: 'Cardiology',
    roomType: 'private',
    tariffAmount: 55000,
    copayAmount: 8000,
    copayPercentage: 15,
    effectiveDate: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'tariff3',
    insurancePartnerId: 'ip2',
    insurancePartnerName: 'Hygeia HMO',
    procedureCode: 'HBA1C-001',
    procedureName: 'HbA1c Test',
    category: 'Laboratory',
    roomType: 'general',
    tariffAmount: 5000,
    effectiveDate: new Date('2023-06-01'),
    status: 'active',
  },
  {
    id: 'tariff4',
    insurancePartnerId: 'ip2',
    insurancePartnerName: 'Hygeia HMO',
    procedureCode: 'LIPID-001',
    procedureName: 'Lipid Profile',
    category: 'Laboratory',
    roomType: 'general',
    tariffAmount: 7000,
    effectiveDate: new Date('2023-06-01'),
    status: 'active',
  },
  {
    id: 'tariff5',
    insurancePartnerId: 'ip4',
    insurancePartnerName: 'National Health Insurance Scheme',
    procedureCode: 'CT-HEAD',
    procedureName: 'CT Scan Head Plain',
    category: 'Radiology',
    roomType: 'general',
    tariffAmount: 35000,
    effectiveDate: new Date('2021-01-01'),
    status: 'active',
  },
];

// ==================== HR MODULE ====================
export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    employeeNumber: 'EMP-2021-001',
    firstName: 'Emeka',
    lastName: 'Adeleke',
    email: 'emeka.adeleke@hosp.com',
    phoneNumber: '+234 802 345 6789',
    dateOfBirth: new Date('1978-03-15'),
    gender: 'male',
    bloodGroup: 'A+',
    address: {
      street: '12 Adeola Odeku Street',
      city: 'Victoria Island',
      state: 'Lagos',
      zipCode: '101241',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Ngozi Adeleke',
      relationship: 'Spouse',
      phoneNumber: '+234 802 345 6790',
    },
    department: 'Cardiology',
    designation: 'Senior Consultant Cardiologist',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2021-06-01'),
    confirmDate: new Date('2021-12-01'),
    qualifications: [
      {
        id: 'qual1',
        degree: 'MBBS',
        institution: 'University of Lagos',
        year: 2002,
        field: 'Medicine',
      },
      {
        id: 'qual2',
        degree: 'FWACP',
        institution: 'National Postgraduate Medical College',
        year: 2010,
        field: 'Cardiology',
      },
    ],
    certifications: [
      {
        id: 'cert1',
        name: 'Cardiology Specialist Certification',
        issuingAuthority: 'Medical and Dental Council of Nigeria',
        issueDate: new Date('2010-11-01'),
        certificateNumber: 'MDCN/2010/12345',
      },
    ],
    experience: 18,
    basicSalary: 850000,
    salaryComponent: {
      basic: 850000,
      hra: 255000,
      da: 85000,
      ta: 85000,
      other: 127500,
    },
    workShift: 'Morning',
    reportingManager: 'Medical Director',
    avatar: '/avatars/adeleke.jpg',
    status: 'active',
  },
  {
    id: 'emp2',
    employeeNumber: 'EMP-2020-002',
    firstName: 'Ibrahim',
    lastName: 'Musa',
    email: 'ibrahim.musa@hosp.com',
    phoneNumber: '+234 803 456 7890',
    dateOfBirth: new Date('1982-07-20'),
    gender: 'male',
    bloodGroup: 'O+',
    address: {
      street: '8 Herbert Macaulay Way',
      city: 'Yaba',
      state: 'Lagos',
      zipCode: '101212',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Aisha Musa',
      relationship: 'Spouse',
      phoneNumber: '+234 803 456 7891',
    },
    department: 'General Medicine',
    designation: 'Consultant Physician',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2020-01-15'),
    confirmDate: new Date('2020-07-15'),
    qualifications: [
      {
        id: 'qual3',
        degree: 'MBBS',
        institution: 'Ahmadu Bello University',
        year: 2006,
        field: 'Medicine',
      },
      {
        id: 'qual4',
        degree: 'FWACP',
        institution: 'West African College of Physicians',
        year: 2014,
        field: 'Internal Medicine',
      },
    ],
    certifications: [],
    experience: 14,
    basicSalary: 750000,
    salaryComponent: {
      basic: 750000,
      hra: 225000,
      da: 75000,
      ta: 75000,
      other: 112500,
    },
    workShift: 'Morning',
    reportingManager: 'Medical Director',
    avatar: '/avatars/ibrahim.jpg',
    status: 'active',
  },
  {
    id: 'emp3',
    employeeNumber: 'EMP-2021-003',
    firstName: 'Chinedu',
    lastName: 'Okonkwo',
    email: 'chinedu.okonkwo@hosp.com',
    phoneNumber: '+234 804 567 8901',
    dateOfBirth: new Date('1985-12-10'),
    gender: 'male',
    bloodGroup: 'B+',
    address: {
      street: '15 Awolowo Road',
      city: 'Ikeja',
      state: 'Lagos',
      zipCode: '100271',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Ngozi Okonkwo',
      relationship: 'Spouse',
      phoneNumber: '+234 804 567 8902',
    },
    department: 'Orthopedics',
    designation: 'Consultant Orthopedic Surgeon',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2021-03-01'),
    confirmDate: new Date('2021-09-01'),
    qualifications: [
      {
        id: 'qual5',
        degree: 'MBBS',
        institution: 'University of Ibadan',
        year: 2009,
        field: 'Medicine',
      },
    ],
    certifications: [],
    experience: 11,
    basicSalary: 780000,
    salaryComponent: {
      basic: 780000,
      hra: 234000,
      da: 78000,
      ta: 78000,
      other: 117000,
    },
    workShift: 'Afternoon',
    reportingManager: 'Medical Director',
    avatar: '/avatars/okonkwo.jpg',
    status: 'active',
  },
  {
    id: 'emp4',
    employeeNumber: 'EMP-2022-004',
    firstName: 'Aisha',
    lastName: 'Yusuf',
    email: 'aisha.yusuf@hosp.com',
    phoneNumber: '+234 805 678 9012',
    dateOfBirth: new Date('1988-05-25'),
    gender: 'female',
    bloodGroup: 'AB+',
    address: {
      street: '42 Isaac John Street',
      city: 'Ikeja GRA',
      state: 'Lagos',
      zipCode: '101271',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Yusuf Mohammed',
      relationship: 'Spouse',
      phoneNumber: '+234 805 678 9013',
    },
    department: 'Pediatrics',
    designation: 'Consultant Pediatrician',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2022-01-10'),
    confirmDate: new Date('2022-07-10'),
    qualifications: [
      {
        id: 'qual6',
        degree: 'MBBS',
        institution: 'University of Lagos',
        year: 2012,
        field: 'Medicine',
      },
    ],
    certifications: [],
    experience: 8,
    basicSalary: 720000,
    salaryComponent: {
      basic: 720000,
      hra: 216000,
      da: 72000,
      ta: 72000,
      other: 108000,
    },
    workShift: 'Morning',
    reportingManager: 'Medical Director',
    avatar: '/avatars/yusuf.jpg',
    status: 'active',
  },
  {
    id: 'emp5',
    employeeNumber: 'EMP-2021-005',
    firstName: 'Chioma',
    lastName: 'Nnamani',
    email: 'chioma.nnamani@hosp.com',
    phoneNumber: '+234 806 789 0123',
    dateOfBirth: new Date('1986-09-14'),
    gender: 'female',
    bloodGroup: 'A+',
    address: {
      street: '23 Airport Road',
      city: 'Ikeja',
      state: 'Lagos',
      zipCode: '100282',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Obiora Nnamani',
      relationship: 'Spouse',
      phoneNumber: '+234 806 789 0124',
    },
    department: 'Neurology',
    designation: 'Consultant Neurologist',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2021-08-01'),
    confirmDate: new Date('2022-02-01'),
    qualifications: [
      {
        id: 'qual7',
        degree: 'MBBS',
        institution: 'University of Nigeria',
        year: 2010,
        field: 'Medicine',
      },
    ],
    certifications: [],
    experience: 10,
    basicSalary: 800000,
    salaryComponent: {
      basic: 800000,
      hra: 240000,
      da: 80000,
      ta: 80000,
      other: 120000,
    },
    workShift: 'Morning',
    reportingManager: 'Medical Director',
    avatar: '/avatars/nnamani.jpg',
    status: 'active',
  },
  {
    id: 'emp6',
    employeeNumber: 'EMP-2023-006',
    firstName: 'Amaka',
    lastName: 'Okafor',
    email: 'amaka.okafor@hosp.com',
    phoneNumber: '+234 807 890 1234',
    dateOfBirth: new Date('1995-03-22'),
    gender: 'female',
    bloodGroup: 'O+',
    address: {
      street: '19 Bishop Oluwole Street',
      city: 'Ikeja',
      state: 'Lagos',
      zipCode: '100275',
      country: 'Nigeria',
    },
    emergencyContact: {
      name: 'Chinedu Okafor',
      relationship: 'Brother',
      phoneNumber: '+234 807 890 1235',
    },
    department: 'General Triage',
    designation: 'Auxiliary Nurse',
    employmentType: 'permanent',
    employmentStatus: 'active',
    joinDate: new Date('2023-02-01'),
    confirmDate: new Date('2023-08-01'),
    qualifications: [
      {
        id: 'qual8',
        degree: 'Nursing Certificate',
        institution: 'School of Nursing Lagos',
        year: 2017,
        field: 'Nursing',
      },
    ],
    certifications: [],
    experience: 5,
    basicSalary: 180000,
    salaryComponent: {
      basic: 180000,
      hra: 54000,
      da: 18000,
      ta: 18000,
      other: 27000,
    },
    workShift: 'Morning',
    reportingManager: 'Head Nurse',
    avatar: '/avatars/nurse_amaka.jpg',
    status: 'active',
  },
];

export const mockShifts: Shift[] = [
  {
    id: 'shift1',
    name: 'Morning Shift',
    code: 'MOR',
    startTime: '08:00',
    endTime: '16:00',
    duration: 8,
    breakDuration: 60,
    department: 'General',
    status: 'active',
  },
  {
    id: 'shift2',
    name: 'Afternoon Shift',
    code: 'AFT',
    startTime: '14:00',
    endTime: '22:00',
    duration: 8,
    breakDuration: 60,
    department: 'General',
    status: 'active',
  },
  {
    id: 'shift3',
    name: 'Night Shift',
    code: 'NGT',
    startTime: '22:00',
    endTime: '08:00',
    duration: 10,
    breakDuration: 60,
    department: 'General',
    status: 'active',
  },
  {
    id: 'shift4',
    name: 'Flexi Shift',
    code: 'FLX',
    startTime: '10:00',
    endTime: '19:00',
    duration: 8,
    breakDuration: 60,
    department: 'Administration',
    status: 'active',
  },
];

export const mockRosterEntries: RosterEntry[] = [
  {
    id: 'rost1',
    employeeId: 'emp1',
    employeeName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    date: new Date('2024-02-05'),
    shift: 'Morning Shift',
    startTime: '08:00',
    endTime: '16:00',
    status: 'scheduled',
    approvedBy: 'Medical Director',
  },
  {
    id: 'rost2',
    employeeId: 'emp2',
    employeeName: 'Dr. Ibrahim Musa',
    department: 'General Medicine',
    date: new Date('2024-02-05'),
    shift: 'Morning Shift',
    startTime: '08:00',
    endTime: '16:00',
    status: 'present',
    checkIn: '07:58',
    checkOut: '16:05',
    workingHours: 8.1,
    approvedBy: 'Medical Director',
  },
  {
    id: 'rost3',
    employeeId: 'emp4',
    employeeName: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    date: new Date('2024-02-05'),
    shift: 'Afternoon Shift',
    startTime: '14:00',
    endTime: '22:00',
    status: 'scheduled',
    approvedBy: 'Medical Director',
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att1',
    employeeId: 'emp1',
    employeeName: 'Dr. Emeka Adeleke',
    date: new Date('2024-02-05'),
    checkIn: '07:55',
    checkOut: '16:02',
    workingHours: 8.12,
    overtime: 0.12,
    status: 'present',
    location: 'Main Hospital',
    device: 'Biometric-01',
  },
  {
    id: 'att2',
    employeeId: 'emp2',
    employeeName: 'Dr. Ibrahim Musa',
    date: new Date('2024-02-05'),
    checkIn: '07:58',
    checkOut: '16:05',
    workingHours: 8.12,
    overtime: 0.12,
    status: 'present',
    location: 'Main Hospital',
    device: 'Biometric-01',
  },
  {
    id: 'att3',
    employeeId: 'emp3',
    employeeName: 'Dr. Chinedu Okonkwo',
    date: new Date('2024-02-05'),
    checkIn: '08:15',
    checkOut: '16:30',
    workingHours: 8.25,
    overtime: 0.25,
    status: 'late',
    lateBy: 15,
    location: 'Main Hospital',
    device: 'Biometric-02',
    remarks: 'Traffic delay',
  },
  {
    id: 'att4',
    employeeId: 'emp6',
    employeeName: 'Amaka Okafor',
    date: new Date('2024-02-05'),
    checkIn: '08:00',
    checkOut: '14:00',
    workingHours: 6,
    overtime: 0,
    status: 'half_day',
    location: 'Triage Center',
    device: 'Biometric-03',
    remarks: 'Half day for medical appointment',
  },
  {
    id: 'att5',
    employeeId: 'emp4',
    employeeName: 'Dr. Aisha Yusuf',
    date: new Date('2024-02-05'),
    status: 'on_leave',
    workingHours: 0,
    overtime: 0,
    location: 'Main Hospital',
    remarks: 'Annual leave',
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'lv1',
    employeeId: 'emp1',
    employeeName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    leaveType: 'earned',
    fromDate: new Date('2024-02-10'),
    toDate: new Date('2024-02-17'),
    days: 6,
    reason: 'Family vacation',
    status: 'approved',
    appliedDate: new Date('2024-01-25'),
    approvedBy: 'Medical Director',
    approvedDate: new Date('2024-01-26'),
    balanceBefore: 21,
    balanceAfter: 15,
  },
  {
    id: 'lv2',
    employeeId: 'emp2',
    employeeName: 'Dr. Ibrahim Musa',
    department: 'General Medicine',
    leaveType: 'casual',
    fromDate: new Date('2024-02-08'),
    toDate: new Date('2024-02-09'),
    days: 2,
    reason: 'Personal work',
    status: 'pending',
    appliedDate: new Date('2024-02-03'),
    balanceBefore: 12,
    balanceAfter: 10,
  },
  {
    id: 'lv3',
    employeeId: 'emp4',
    employeeName: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    leaveType: 'sick',
    fromDate: new Date('2024-02-05'),
    toDate: new Date('2024-02-07'),
    days: 3,
    reason: 'Medical leave - doctor advised rest',
    status: 'approved',
    appliedDate: new Date('2024-02-04'),
    approvedBy: 'Medical Director',
    approvedDate: new Date('2024-02-04'),
    attachmentUrl: '/documents/sick-leave-cert.pdf',
    balanceBefore: 10,
    balanceAfter: 7,
  },
  {
    id: 'lv4',
    employeeId: 'emp3',
    employeeName: 'Dr. Chinedu Okonkwo',
    department: 'Orthopedics',
    leaveType: 'earned',
    fromDate: new Date('2024-02-20'),
    toDate: new Date('2024-02-28'),
    days: 7,
    reason: 'Attend conference',
    status: 'pending',
    appliedDate: new Date('2024-02-01'),
    balanceBefore: 18,
    balanceAfter: 11,
  },
];

export const mockLeaveBalances: LeaveBalance[] = [
  {
    employeeId: 'emp1',
    employeeName: 'Dr. Emeka Adeleke',
    casualLeave: { total: 12, used: 3, balance: 9 },
    sickLeave: { total: 10, used: 1, balance: 9 },
    earnedLeave: { total: 21, used: 6, balance: 15 },
    compensatoryLeave: { total: 5, used: 0, balance: 5 },
  },
  {
    employeeId: 'emp2',
    employeeName: 'Dr. Ibrahim Musa',
    casualLeave: { total: 12, used: 2, balance: 10 },
    sickLeave: { total: 10, used: 0, balance: 10 },
    earnedLeave: { total: 18, used: 3, balance: 15 },
    compensatoryLeave: { total: 3, used: 0, balance: 3 },
  },
  {
    employeeId: 'emp4',
    employeeName: 'Dr. Aisha Yusuf',
    casualLeave: { total: 12, used: 4, balance: 8 },
    sickLeave: { total: 10, used: 3, balance: 7 },
    earnedLeave: { total: 15, used: 5, balance: 10 },
    compensatoryLeave: { total: 4, used: 0, balance: 4 },
  },
];

export const mockPayrolls: Payroll[] = [
  {
    id: 'pay1',
    payrollNumber: 'PAY-2024-0201',
    employeeId: 'emp1',
    employeeName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    month: 1,
    year: 2024,
    payDate: new Date('2024-01-31'),
    earnings: {
      basic: 850000,
      hra: 255000,
      da: 85000,
      ta: 85000,
      other: 127500,
      arrears: 0,
      overtime: 45000,
      total: 1447500,
    },
    deductions: {
      pf: 85000,
      esi: 12500,
      tax: 285000,
      professionalTax: 2000,
      other: 0,
      total: 384500,
    },
    netPayable: 1063000,
    paymentMode: 'bank_transfer',
    status: 'paid',
    processedBy: 'Accounts Department',
    processedDate: new Date('2024-01-30'),
  },
  {
    id: 'pay2',
    payrollNumber: 'PAY-2024-0202',
    employeeId: 'emp2',
    employeeName: 'Dr. Ibrahim Musa',
    department: 'General Medicine',
    month: 1,
    year: 2024,
    payDate: new Date('2024-01-31'),
    earnings: {
      basic: 750000,
      hra: 225000,
      da: 75000,
      ta: 75000,
      other: 112500,
      arrears: 0,
      overtime: 30000,
      total: 1267500,
    },
    deductions: {
      pf: 75000,
      esi: 11000,
      tax: 245000,
      professionalTax: 2000,
      other: 0,
      total: 333000,
    },
    netPayable: 934500,
    paymentMode: 'bank_transfer',
    status: 'paid',
    processedBy: 'Accounts Department',
    processedDate: new Date('2024-01-30'),
  },
  {
    id: 'pay3',
    payrollNumber: 'PAY-2024-0203',
    employeeId: 'emp6',
    employeeName: 'Amaka Okafor',
    department: 'General Triage',
    month: 1,
    year: 2024,
    payDate: new Date('2024-01-31'),
    earnings: {
      basic: 180000,
      hra: 54000,
      da: 18000,
      ta: 18000,
      other: 27000,
      arrears: 0,
      overtime: 8000,
      total: 305000,
    },
    deductions: {
      pf: 18000,
      esi: 4500,
      tax: 35000,
      professionalTax: 2000,
      other: 0,
      total: 59500,
    },
    netPayable: 245500,
    paymentMode: 'bank_transfer',
    status: 'paid',
    processedBy: 'Accounts Department',
    processedDate: new Date('2024-01-30'),
  },
];

export const mockDepartments: HRDepartment[] = [
  {
    id: 'dept1',
    name: 'Cardiology',
    code: 'CARD',
    headOfDepartment: 'Dr. Emeka Adeleke',
    location: '2nd Floor, Block A',
    floor: '2',
    extension: '201',
    email: 'cardiology@hosp.com',
    budget: 15000000,
    spent: 8500000,
    employees: 8,
    status: 'active',
    description: 'Diagnosis and treatment of heart and cardiovascular conditions',
  },
  {
    id: 'dept2',
    name: 'General Medicine',
    code: 'GM',
    headOfDepartment: 'Dr. Ibrahim Musa',
    location: '1st Floor, Block A',
    floor: '1',
    extension: '101',
    email: 'generalmedicine@hosp.com',
    budget: 12000000,
    spent: 6800000,
    employees: 12,
    status: 'active',
    description: 'General medical care and internal medicine',
  },
  {
    id: 'dept3',
    name: 'Orthopedics',
    code: 'ORTHO',
    headOfDepartment: 'Dr. Chinedu Okonkwo',
    location: '3rd Floor, Block B',
    floor: '3',
    extension: '301',
    email: 'orthopedics@hosp.com',
    budget: 10000000,
    spent: 5200000,
    employees: 6,
    status: 'active',
    description: 'Bone and joint treatment and surgery',
  },
  {
    id: 'dept4',
    name: 'Pediatrics',
    code: 'PEDIA',
    headOfDepartment: 'Dr. Aisha Yusuf',
    location: 'Ground Floor, Block C',
    floor: '0',
    extension: '401',
    email: 'pediatrics@hosp.com',
    budget: 8000000,
    spent: 4500000,
    employees: 10,
    status: 'active',
    description: 'Child and adolescent healthcare',
  },
  {
    id: 'dept5',
    name: 'Neurology',
    code: 'NEURO',
    headOfDepartment: 'Dr. Chioma Nnamani',
    location: '2nd Floor, Block B',
    floor: '2',
    extension: '251',
    email: 'neurology@hosp.com',
    budget: 11000000,
    spent: 5800000,
    employees: 5,
    status: 'active',
    description: 'Diagnosis and treatment of nervous system disorders',
  },
  {
    id: 'dept6',
    name: 'General Triage',
    code: 'TRIAGE',
    headOfDepartment: 'Head Nurse',
    location: 'Ground Floor, Main Building',
    floor: '0',
    extension: '001',
    email: 'triage@hosp.com',
    budget: 3000000,
    spent: 1800000,
    employees: 8,
    status: 'active',
    description: 'Initial patient assessment and triage',
  },
];

// ==================== EMERGENCY MODULE ====================
export const mockEmergencyPatients: EmergencyPatient[] = [
  {
    id: 'ed1',
    visitNumber: 'EDV-2024-0001',
    patientId: '1',
    patientName: 'Chukwuemeka Okonkwo',
    mrn: 'MRN-2024-0001',
    age: 44,
    gender: 'male',
    contactNumber: '+234 803 456 7890',
    arrivalDate: new Date('2024-02-05T08:30:00'),
    arrivalMode: 'ambulance',
    referredBy: 'Lagos General Hospital',
    triageLevel: 2,
    chiefComplaint: 'Severe chest pain and shortness of breath',
    vitals: {
      bloodPressure: '165/105',
      pulse: 118,
      temperature: 37.8,
      spO2: 91,
      respiratoryRate: 26,
      painScore: 8,
    },
    allergies: ['Penicillin', 'Groundnuts'],
    assignedDoctor: 'Dr. Emeka Adeleke',
    assignedNurse: 'Amaka Okafor',
    bed: 'ED-02',
    status: 'in_examination',
    notes: 'Patient brought in by ambulance, stable but critical',
  },
  {
    id: 'ed2',
    visitNumber: 'EDV-2024-0002',
    patientId: '7',
    patientName: 'Tobi Okafor',
    mrn: 'MRN-2024-0007',
    age: 5,
    gender: 'male',
    contactNumber: '+234 802 123 4567',
    arrivalDate: new Date('2024-02-05T09:15:00'),
    arrivalMode: 'walk_in',
    triageLevel: 3,
    chiefComplaint: 'Difficulty breathing and wheezing',
    vitals: {
      bloodPressure: '95/60',
      pulse: 125,
      temperature: 37.2,
      spO2: 93,
      respiratoryRate: 32,
      painScore: 4,
    },
    allergies: ['Peanuts'],
    assignedDoctor: 'Dr. Aisha Yusuf',
    assignedNurse: 'Grace Adebayo',
    bed: 'ED-PED-01',
    status: 'in_examination',
    notes: 'Asthma exacerbation, nebulizer administered',
  },
  {
    id: 'ed3',
    visitNumber: 'EDV-2024-0003',
    patientId: '3',
    patientName: 'Olufemi Adebayo',
    mrn: 'MRN-2024-0003',
    age: 59,
    gender: 'male',
    contactNumber: '+234 806 789 0123',
    arrivalDate: new Date('2024-02-05T07:45:00'),
    arrivalMode: 'walk_in',
    triageLevel: 4,
    chiefComplaint: 'High fever and body aches',
    vitals: {
      bloodPressure: '130/85',
      pulse: 92,
      temperature: 39.2,
      spO2: 97,
      respiratoryRate: 18,
      painScore: 6,
    },
    allergies: ['Aspirin'],
    assignedDoctor: 'Dr. Ibrahim Musa',
    bed: 'ED-05',
    status: 'waiting',
    notes: 'Suspected malaria, awaiting lab results',
  },
  {
    id: 'ed4',
    visitNumber: 'EDV-2024-0004',
    patientId: '2',
    patientName: 'Adanna Okafor',
    mrn: 'MRN-2024-0002',
    age: 32,
    gender: 'female',
    contactNumber: '+234 810 123 4567',
    arrivalDate: new Date('2024-02-05T06:20:00'),
    arrivalMode: 'ambulance',
    referredBy: 'Family Health Clinic',
    triageLevel: 1,
    chiefComplaint: 'Road traffic accident - multiple injuries',
    vitals: {
      bloodPressure: '80/50',
      pulse: 135,
      temperature: 36.5,
      spO2: 88,
      respiratoryRate: 28,
      painScore: 9,
    },
    allergies: [],
    assignedDoctor: 'Dr. Chinedu Okonkwo',
    assignedNurse: 'Chinedu Eze',
    bed: 'ED-TRAUMA-01',
    status: 'admitted',
    disposition: 'admitted',
    dispositionDate: new Date('2024-02-05T07:30:00'),
    dispositionNotes: 'Admitted to Orthopedics ICU - multiple fractures',
  },
  {
    id: 'ed5',
    visitNumber: 'EDV-2024-0005',
    patientId: '5',
    patientName: 'Ibrahim Musah',
    mrn: 'MRN-2024-0005',
    age: 49,
    gender: 'male',
    contactNumber: '+234 804 567 8901',
    arrivalDate: new Date('2024-02-05T10:00:00'),
    arrivalMode: 'walk_in',
    triageLevel: 5,
    chiefComplaint: 'Minor cut on finger',
    vitals: {
      bloodPressure: '125/80',
      pulse: 78,
      temperature: 36.8,
      spO2: 99,
      painScore: 2,
    },
    allergies: ['Dust'],
    assignedNurse: 'Funmilayo Adewale',
    status: 'discharged',
    disposition: 'discharged_home',
    dispositionDate: new Date('2024-02-05T10:45:00'),
    dispositionNotes: 'Wound dressed and discharged',
    notes: 'Minor injury, treated and discharged',
  },
];

export const mockEDBoard: EDBoard[] = [
  {
    id: 'edb1',
    patientId: '1',
    patientName: 'Chukwuemeka Okonkwo',
    mrn: 'MRN-2024-0001',
    visitNumber: 'EDV-2024-0001',
    triageLevel: 2,
    chiefComplaint: 'Severe chest pain',
    arrivalTime: new Date('2024-02-05T08:30:00'),
    duration: 45,
    bed: 'ED-02',
    assignedDoctor: 'Dr. Emeka Adeleke',
    status: 'in_progress',
  },
  {
    id: 'edb2',
    patientId: '7',
    patientName: 'Tobi Okafor',
    mrn: 'MRN-2024-0007',
    visitNumber: 'EDV-2024-0002',
    triageLevel: 3,
    chiefComplaint: 'Breathing difficulty',
    arrivalTime: new Date('2024-02-05T09:15:00'),
    duration: 20,
    bed: 'ED-PED-01',
    assignedDoctor: 'Dr. Aisha Yusuf',
    status: 'in_progress',
  },
  {
    id: 'edb3',
    patientId: '3',
    patientName: 'Olufemi Adebayo',
    mrn: 'MRN-2024-0003',
    visitNumber: 'EDV-2024-0003',
    triageLevel: 4,
    chiefComplaint: 'High fever',
    arrivalTime: new Date('2024-02-05T07:45:00'),
    duration: 110,
    status: 'waiting',
  },
  {
    id: 'edb4',
    patientId: '2',
    patientName: 'Adanna Okafor',
    mrn: 'MRN-2024-0002',
    visitNumber: 'EDV-2024-0004',
    triageLevel: 1,
    chiefComplaint: 'RTA - Multiple injuries',
    arrivalTime: new Date('2024-02-05T06:20:00'),
    duration: 185,
    bed: 'ED-TRAUMA-01',
    assignedDoctor: 'Dr. Chinedu Okonkwo',
    status: 'admitted',
  },
];

export const mockEDStats: EDStats = {
  totalPatients: 5,
  waiting: 1,
  inProgress: 2,
  admitted: 1,
  discharged: 1,
  critical: 2,
  averageWaitTime: 45,
  averageTreatmentTime: 65,
  bedOccupancy: 4,
  totalBeds: 10,
};

// ==================== TELEMEDICINE MODULE ====================
export const mockTelemedicineConsultations: TelemedicineConsultation[] = [
  {
    id: 'tele1',
    consultationNumber: 'TC-2024-0001',
    patientId: '1',
    patientName: 'Chukwuemeka Okonkwo',
    mrn: 'MRN-2024-0001',
    doctorId: 'd1',
    doctorName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    scheduledDate: new Date('2024-02-06'),
    scheduledTime: '10:00',
    duration: 30,
    status: 'scheduled',
    type: 'video',
    chiefComplaint: 'Follow-up for hypertension',
    followUpRequired: false,
    joiningLink: 'https://meet.hosp.com/tele1',
  },
  {
    id: 'tele2',
    consultationNumber: 'TC-2024-0002',
    patientId: '7',
    patientName: 'Tobi Okafor',
    mrn: 'MRN-2024-0007',
    doctorId: 'd4',
    doctorName: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    scheduledDate: new Date('2024-02-05'),
    scheduledTime: '14:00',
    duration: 20,
    status: 'completed',
    type: 'video',
    chiefComplaint: 'Asthma follow-up',
    diagnosis: 'Childhood Asthma - Stable',
    prescription: 'Continue Budecort 100mcg twice daily',
    notes: 'Patient stable, continue current medication',
    followUpRequired: true,
    followUpDate: new Date('2024-03-05'),
    rating: 5,
    patientFeedback: 'Very good consultation',
    recordingUrl: '/recordings/tele2.mp4',
  },
  {
    id: 'tele3',
    consultationNumber: 'TC-2024-0003',
    patientId: '3',
    patientName: 'Olufemi Adebayo',
    mrn: 'MRN-2024-0003',
    doctorId: 'd2',
    doctorName: 'Dr. Ibrahim Musa',
    department: 'General Medicine',
    scheduledDate: new Date('2024-02-04'),
    scheduledTime: '16:00',
    duration: 30,
    status: 'no_show',
    type: 'video',
    chiefComplaint: 'Diabetes follow-up',
    followUpRequired: true,
    notes: 'Patient did not join the consultation',
  },
  {
    id: 'tele4',
    consultationNumber: 'TC-2024-0004',
    patientId: '2',
    patientName: 'Adanna Okafor',
    mrn: 'MRN-2024-0002',
    doctorId: 'd3',
    doctorName: 'Dr. Chinedu Okonkwo',
    department: 'Orthopedics',
    scheduledDate: new Date('2024-02-07'),
    scheduledTime: '11:00',
    duration: 30,
    status: 'confirmed',
    type: 'audio',
    chiefComplaint: 'Knee pain consultation',
    followUpRequired: false,
  },
  {
    id: 'tele5',
    consultationNumber: 'TC-2024-0005',
    patientId: '5',
    patientName: 'Ibrahim Musah',
    mrn: 'MRN-2024-0005',
    doctorId: 'd5',
    doctorName: 'Dr. Chioma Nnamani',
    department: 'Neurology',
    scheduledDate: new Date('2024-02-08'),
    scheduledTime: '15:00',
    duration: 45,
    status: 'scheduled',
    type: 'video',
    chiefComplaint: 'Migraine follow-up consultation',
    followUpRequired: false,
  },
];

export const mockTelemedicineSlots: TelemedicineSlot[] = [
  {
    id: 'slot1',
    doctorId: 'd1',
    doctorName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    date: new Date('2024-02-06'),
    startTime: '09:00',
    endTime: '09:30',
    duration: 30,
    available: true,
  },
  {
    id: 'slot2',
    doctorId: 'd1',
    doctorName: 'Dr. Emeka Adeleke',
    department: 'Cardiology',
    date: new Date('2024-02-06'),
    startTime: '10:00',
    endTime: '10:30',
    duration: 30,
    available: false,
    bookedBy: 'Chukwuemeka Okonkwo',
  },
  {
    id: 'slot3',
    doctorId: 'd4',
    doctorName: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    date: new Date('2024-02-06'),
    startTime: '14:00',
    endTime: '14:20',
    duration: 20,
    available: true,
  },
  {
    id: 'slot4',
    doctorId: 'd4',
    doctorName: 'Dr. Aisha Yusuf',
    department: 'Pediatrics',
    date: new Date('2024-02-06'),
    startTime: '14:30',
    endTime: '14:50',
    duration: 20,
    available: true,
  },
];
