'use client';

import React from 'react';
import { Table, Button, Badge, Tag, Card, Input } from 'antd';
import { FileTextOutlined, SearchOutlined, DownloadOutlined, PrinterOutlined } from '@ant-design/icons';
import { formatDate } from '@/lib/utils';

interface LabReport {
  id: string;
  reportNumber: string;
  patientName: string;
  testType: string;
  generatedDate: Date;
  generatedBy: string;
  status: 'final' | 'preliminary';
}

const mockLabReports: LabReport[] = [
  { id: 'lr1', reportNumber: 'LR-2024-001', patientName: 'Chukwuemeka Okonkwo', testType: 'Complete Blood Count', generatedDate: new Date('2024-02-05'), generatedBy: 'Lab System', status: 'final' },
  { id: 'lr2', reportNumber: 'LR-2024-002', patientName: 'Adanna Okafor', testType: 'Lipid Profile', generatedDate: new Date('2024-02-05'), generatedBy: 'Lab Tech 1', status: 'preliminary' },
  { id: 'lr3', reportNumber: 'LR-2024-003', patientName: 'Tobi Okafor', testType: 'Malaria Parasite', generatedDate: new Date('2024-02-04'), generatedBy: 'Lab Tech 2', status: 'final' },
];

export default function LabReportsPage() {
  const [searchText, setSearchText] = React.useState('');

  const filteredReports = mockLabReports.filter((report) => {
    return (
      report.patientName.toLowerCase().includes(searchText.toLowerCase()) ||
      report.reportNumber.toLowerCase().includes(searchText.toLowerCase())
    );
  });

  const columns = [
    { title: 'Report Number', dataIndex: 'reportNumber', key: 'reportNumber' },
    { title: 'Patient', dataIndex: 'patientName', key: 'patient' },
    { title: 'Test Type', dataIndex: 'testType', key: 'testType' },
    {
      title: 'Generated',
      dataIndex: 'generatedDate',
      key: 'generated',
      render: (d: Date) => formatDate(d),
    },
    { title: 'Generated By', dataIndex: 'generatedBy', key: 'by' },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => (
        <Tag color={status === 'final' ? 'success' : 'warning'}>{status.toUpperCase()}</Tag>
      ),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: () => (
        <div className="flex gap-2">
          <Button size="small" icon={<DownloadOutlined />}>Download</Button>
          <Button size="small" icon={<PrinterOutlined />}>Print</Button>
        </div>
      ),
    },
  ];

  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(180deg, #F0F9FF 0%, #F8FAFC 100%)', padding: '24px' }}>
      <div style={{ background: 'white', borderRadius: '12px', padding: '24px', border: '1px solid #E2E8F0' }}>
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-semibold text-gray-900 mb-1 flex items-center gap-2">
              <FileTextOutlined style={{ color: '#10B981' }} />
              Lab Reports
            </h1>
            <p className="text-gray-500 text-sm">Generate and manage laboratory reports</p>
          </div>
        </div>

        <div className="flex items-center gap-3 mb-6">
          <Input placeholder="Search reports..." prefix={<SearchOutlined />} value={searchText} onChange={(e) => setSearchText(e.target.value)} style={{ flex: 1, maxWidth: '400px' }} />
          <Badge count={filteredReports.length} style={{ background: '#10B981' }} />
        </div>

        <Table dataSource={filteredReports} columns={columns} rowKey="id" pagination={{ defaultPageSize: 10 }} size="middle" />
      </div>
    </div>
  );
}
